# Generated by Django 3.0.7 on 2020-06-16 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numcasosobitoscidade',
            name='data_coleta',
            field=models.DateField(default=datetime.date(2020, 6, 15), verbose_name='Data de coleta'),
        ),
    ]
