# Generated by Django 3.0.7 on 2020-06-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_numcasosobitoscidade_data_coleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestesRapidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negativos', models.IntegerField(verbose_name='Teste Rápido Não Reagente')),
                ('positivos', models.IntegerField(verbose_name='Teste Rápido Reagente')),
                ('total', models.IntegerField(verbose_name='Total TR')),
                ('data_coleta', models.DateField(verbose_name='Data de coleta')),
            ],
        ),
        migrations.AlterField(
            model_name='numcasosobitoscidade',
            name='data_coleta',
            field=models.DateField(verbose_name='Data de coleta'),
        ),
    ]
