# Generated by Django 3.0.7 on 2020-06-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_confirmadossexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObitosSexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masculino', models.IntegerField(verbose_name='Masculino')),
                ('feminino', models.IntegerField(verbose_name='Feminino')),
                ('data_coleta', models.DateField(verbose_name='Data de coleta')),
            ],
        ),
    ]
