# Generated by Django 3.0.7 on 2020-06-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faixaetaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaixaEtaria',
        ),
    ]
