# Generated by Django 3.0.7 on 2020-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_faixaetaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(max_length=50, verbose_name='Faixa Etária')),
                ('confirmados', models.IntegerField(verbose_name='Confirmados')),
                ('obitos', models.IntegerField(verbose_name='Óbitos')),
                ('percentual_conf', models.FloatField(verbose_name='Percentual Confirmados')),
                ('percentual_obt', models.FloatField(verbose_name='Percentual Óbitos')),
                ('data_coleta', models.DateField(verbose_name='Data de coleta')),
            ],
        ),
    ]
