# Generated by Django 3.0.7 on 2020-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faixaetaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morbidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbidade', models.CharField(max_length=50, verbose_name='Faixa Etária')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('percentual', models.FloatField(verbose_name='Percentual')),
                ('data_coleta', models.DateField(verbose_name='Data de coleta')),
            ],
        ),
    ]
