# Generated by Django 3.0.7 on 2020-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_casospordia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasosPorSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(unique=True, verbose_name='Semana')),
                ('confirmados', models.IntegerField(verbose_name='Confirmados')),
                ('obitos', models.IntegerField(verbose_name='Óbitos')),
                ('novos', models.IntegerField(verbose_name='Novos casos por semana')),
            ],
        ),
    ]
