# Generated by Django 3.0.7 on 2020-06-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_casosporsemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(unique=True, verbose_name='Dia')),
                ('capacidade_leitos_clinicos', models.IntegerField(verbose_name='Capacidade leitos clinicos')),
                ('internados_leitos_clinicos', models.IntegerField(verbose_name='Internados leitos clinicos')),
                ('capacidade_UTI', models.IntegerField(verbose_name='Capacidade UTI')),
                ('internados_UTI', models.IntegerField(verbose_name='Internados UTI')),
                ('capacidade_leitos_estabilizacao', models.IntegerField(verbose_name='Capacidade leitos estabilização')),
                ('internados_leitos_estabilizacao', models.IntegerField(verbose_name='Internados leitos estabilização')),
                ('capacidade_leitos_respiradores', models.IntegerField(verbose_name='Capacidade leitos respiradores')),
                ('internados_leitos_respiradores', models.IntegerField(verbose_name='Internados leitos respiradores')),
                ('altas', models.IntegerField(null=True, verbose_name='Altas')),
            ],
        ),
    ]
