# Generated by Django 3.0.7 on 2020-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_leitos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('confirmados', models.IntegerField(verbose_name='Confirmados')),
                ('obitos', models.IntegerField(verbose_name='Óbitos')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('ibge_id', models.IntegerField(verbose_name='IBGE ID')),
            ],
            options={
                'verbose_name': 'HistoricoCidade',
                'verbose_name_plural': 'HistoricoCidades',
            },
        ),
    ]
